{
  parserClass="net.postchain.rellide.jetbrains.language.parser.RellParser"
  parserUtilClass="net.postchain.rellide.jetbrains.language.parser.RellParserUtil"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Rell"
  psiImplClassSuffix="Impl"
  psiPackage="net.postchain.rellide.jetbrains.language.psi"
  psiImplPackage="net.postchain.rellide.jetbrains.language.psi.impl"

  elementTypeHolderClass="net.postchain.rellide.jetbrains.language.psi.RellTypes"
  elementTypeClass="net.postchain.rellide.jetbrains.language.psi.RellElementType"
  tokenTypeClass="net.postchain.rellide.jetbrains.language.psi.RellTokenType"

  psiImplUtilClass="net.postchain.rellide.jetbrains.language.psi.impl.RellPsiImplUtil"

  tokens=[
    space='regexp:\s+'
    booleanLiteral='regexp:true|false'

    SL_COMMENT="regexp://.*"
    ML_COMMENT="regexp:/\*([^*]|[\r\n]|(\*+([^*/]|[\r\n])))*\*+/"

    WS="regexp:(' '|'\t'|'\r'|'\n')+"
    ID='regexp:[a-zA-Z_$][a-zA-Z_$0-9]*'
    DECNUM="regexp:[0-9]+"
    DECIMAL="regexp:[-+]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?"
    HEXDIG="regexp:[0-9]|[A-F]|[a-f]"
    BYTES="regexp:x(('[_0-9a-fA-F]+')|(\"[_0-9a-fA-F]+\"))"
    STRBAD="regexp:\\|'\u0000' .. '\u001F'"

    STRING="regexp:(\"([^\"\r\n\\]|\\.)*\")|('([^'\r\n\\]|\\.)*')"
  ]
}

X_RootParser ::= (X_ModuleHeader)? (X_AnnotatedDef)*


X_ModuleHeader ::= (X_Modifier)* X_tkMODULE ';'


X_Modifier ::= 'abstract'
   | 'override'
   | X_Annotation


X_Annotation ::= '@' X_Name (X_AnnotationArgs)?


X_Name ::= ID


X_AnnotationArgs ::= '(' (X_AnnotationArg (',' X_AnnotationArg)*)? ')'


X_AnnotationArg ::= X_AnnotationArgValue
   | X_AnnotationArgName


X_AnnotationArgValue ::= X_LiteralExpr


X_LiteralExpr ::= X_IntExpr
   | X_BigIntExpr
   | X_DecimalExpr
   | X_StringExpr
   | X_BytesExpr
   | 'false'
   | 'true'
   | X_NullLiteralExpr


X_IntExpr ::= NUMBER


X_BigIntExpr ::= BIG_INTEGER


X_DecimalExpr ::= DECIMAL


X_StringExpr ::= STRING


X_BytesExpr ::= BYTES


X_NullLiteralExpr ::= 'null'


X_AnnotationArgName ::= X_QualifiedName


X_QualifiedName ::= X_Name ('.' X_Name)*


X_tkMODULE ::= 'module'


X_AnnotatedDef ::= (X_Modifier)* X_AnyDef


X_AnyDef ::= X_EntityDef
   | X_ObjectDef
   | X_StructDef
   | X_EnumDef
   | X_FunctionDef
   | X_NamespaceDef
   | X_ImportDef
   | X_OpDef
   | X_QueryDef
   | X_IncludeDef
   | X_ConstantDef


X_EntityDef ::= X_EntityKeyword X_Name (X_EntityAnnotations)? (X_EntityBody)?


X_EntityKeyword ::= 'entity'
   | 'class'


X_EntityAnnotations ::= '(' X_Name (',' X_Name)* ')'


X_EntityBody ::= X_EntityBodyFull
   | X_EntityBodyShort


X_EntityBodyFull ::= '{' (X_RelAnyClause)* '}'


X_RelAnyClause ::= X_RelAttributeClause
   | X_RelKeyIndexClause


X_RelAttributeClause ::= X_AttributeDefinition


X_AttributeDefinition ::= X_BaseAttributeDefinition ';'


X_BaseAttributeDefinition ::= (X_tkMUTABLE)? X_AttrHeader ('=' X_ExpressionRef)?


X_tkMUTABLE ::= 'mutable'


X_AttrHeader ::= X_NameTypeAttrHeader
   | X_AnonAttrHeader


X_NameTypeAttrHeader ::= X_Name ':' X_Type


X_Type ::= X_ComplexNullableType
   | X_FunctionType
   | X_BasicType


X_ComplexNullableType ::= X_tkLPAR X_TypeRef ')' '?'


X_tkLPAR ::= '('


X_TypeRef ::= X_Type


X_FunctionType ::= X_tkLPAR (X_TypeRef (',' X_TypeRef)*)? ')' '->' X_TypeRef


X_BasicType ::= X_PrimaryType (X_tkQUESTION)*


X_PrimaryType ::= X_GenericType
   | X_NameType
   | X_TupleType
   | X_VirtualType
   | X_MirrorStructType


X_GenericType ::= X_QualifiedName '<' X_TypeRef (',' X_TypeRef)* '>'


X_NameType ::= X_QualifiedName


X_TupleType ::= X_tkLPAR X_TupleTypeField (X_TupleTypeTail)? ')'


X_TupleTypeField ::= (X_Name ':')? X_TypeRef


X_TupleTypeTail ::= ',' (X_TupleTypeField (',' X_TupleTypeField)*)?


X_VirtualType ::= X_tkVIRTUAL '<' X_TypeRef '>'


X_tkVIRTUAL ::= 'virtual'


X_MirrorStructType ::= X_MirrorStructType0


X_MirrorStructType0 ::= X_tkSTRUCT '<' (X_tkMUTABLE)? X_TypeRef '>'


X_tkSTRUCT ::= 'struct'


X_tkQUESTION ::= '?'


X_AnonAttrHeader ::= X_QualifiedName (X_tkQUESTION)?


X_ExpressionRef ::= X_Expression


X_Expression ::= X_UnaryExpr (X_BinaryExprOperand)*


X_UnaryExpr ::= (X_UnaryPrefixOperator)* X_OperandExpr


X_UnaryPrefixOperator ::= '+'
   | '-'
   | 'not'
   | X_IncrementOperator


X_IncrementOperator ::= '++'
   | '--'


X_OperandExpr ::= X_BaseExpr
   | X_IfExpr
   | X_WhenExpr


X_BaseExpr ::= X_BaseExprHead (X_BaseExprTail)*


X_BaseExprHead ::= X_GenericTypeExpr
   | X_NameExpr
   | X_DollarExpr
   | X_AttrExpr
   | X_IntExpr
   | X_BigIntExpr
   | X_DecimalExpr
   | X_StringExpr
   | X_BytesExpr
   | 'false'
   | 'true'
   | X_NullLiteralExpr
   | X_ParenthesesExpr
   | X_CreateExpr
   | X_ListLiteralExpr
   | X_EmptyMapLiteralExpr
   | X_NonEmptyMapLiteralExpr
   | X_MirrorStructExpr
   | X_VirtualTypeExpr


X_GenericTypeExpr ::= X_GenericType (X_BaseExprTailMember | X_BaseExprTailCall)


X_BaseExprTailMember ::= '.' X_Name


X_BaseExprTailCall ::= X_CallArgs


X_CallArgs ::= '(' (X_CallArg (',' X_CallArg)*)? ')'


X_CallArg ::= (X_Name '=')? X_CallArgValue


X_CallArgValue ::= '*'
   | X_ExpressionRef


X_NameExpr ::= X_Name


X_DollarExpr ::= '$'


X_AttrExpr ::= X_tkDOT X_Name


X_tkDOT ::= '.'


X_ParenthesesExpr ::= X_tkLPAR X_TupleExprField (X_TupleExprTail)? ')'


X_TupleExprField ::= X_TupleExprFieldNameEqExpr
   | X_TupleExprFieldNameColonExpr
   | X_TupleExprFieldExpr


X_TupleExprFieldNameEqExpr ::= X_Name X_tkASSIGN X_ExpressionRef


X_tkASSIGN ::= '='


X_TupleExprFieldNameColonExpr ::= X_Name X_tkCOLON X_ExpressionRef


X_tkCOLON ::= ':'


X_TupleExprFieldExpr ::= X_ExpressionRef


X_TupleExprTail ::= ',' (X_TupleExprField (',' X_TupleExprField)*)?


X_CreateExpr ::= X_tkCREATE X_QualifiedName '(' (X_CreateExprArg (',' X_CreateExprArg)*)? ')'


X_tkCREATE ::= 'create'


X_CreateExprArg ::= (('.')? X_Name '=')? X_CallArgValue


X_ListLiteralExpr ::= X_tkLBRACK (X_ExpressionRef (',' X_ExpressionRef)*)? ']'


X_tkLBRACK ::= '['


X_EmptyMapLiteralExpr ::= X_tkLBRACK ':' ']'


X_NonEmptyMapLiteralExpr ::= X_tkLBRACK X_MapLiteralExprEntry (',' X_MapLiteralExprEntry)* ']'


X_MapLiteralExprEntry ::= X_ExpressionRef ':' X_ExpressionRef


X_MirrorStructExpr ::= X_MirrorStructType0


X_VirtualTypeExpr ::= X_VirtualType


X_BaseExprTail ::= X_BaseExprTailMember
   | X_BaseExprTailSubscript
   | X_BaseExprTailNotNull
   | X_BaseExprTailSafeMember
   | X_BaseExprTailUnaryPostfixOp
   | X_BaseExprTailCall
   | X_BaseExprTailAt


X_BaseExprTailSubscript ::= X_tkLBRACK X_ExpressionRef ']'


X_BaseExprTailNotNull ::= '!!'


X_BaseExprTailSafeMember ::= '?.' X_Name


X_BaseExprTailUnaryPostfixOp ::= X_UnaryPostfixOperator


X_UnaryPostfixOperator ::= X_IncrementOperator
   | '??'


X_BaseExprTailAt ::= X_AtExprAt X_AtExprWhere (X_AtExprWhat)? (X_AtExprModifiers)?


X_AtExprAt ::= X_tkAT X_tkQUESTION
   | X_tkAT X_tkMUL
   | X_tkAT X_tkPLUS
   | '@'


X_tkAT ::= '@'


X_tkMUL ::= '*'


X_tkPLUS ::= '+'


X_AtExprWhere ::= '{' (X_ExpressionRef (',' X_ExpressionRef)*)? '}'


X_AtExprWhat ::= X_AtExprWhatSimple
   | X_AtExprWhatComplex


X_AtExprWhatSimple ::= ('.' X_Name)+


X_AtExprWhatComplex ::= '(' X_AtExprWhatComplexItem (',' X_AtExprWhatComplexItem)* ')'


X_AtExprWhatComplexItem ::= (X_Annotation)* (X_AtExprWhatName)? X_ExpressionRef


X_AtExprWhatName ::= X_Name '='


X_AtExprModifiers ::= 'limit' X_ExpressionRef (X_AtExprOffset)?
   | 'offset' X_ExpressionRef (X_AtExprLimit)?


X_AtExprOffset ::= 'offset' X_ExpressionRef


X_AtExprLimit ::= 'limit' X_ExpressionRef


X_IfExpr ::= X_tkIF '(' X_ExpressionRef ')' X_ExpressionRef 'else' X_ExpressionRef


X_tkIF ::= 'if'


X_WhenExpr ::= X_tkWHEN ('(' X_ExpressionRef ')')? '{' X_WhenExprCases '}'


X_tkWHEN ::= 'when'


X_WhenExprCases ::= X_WhenExprCase ((';')+ X_WhenExprCase)* (X_tkSEMI)*


X_WhenExprCase ::= X_WhenCondition '->' X_ExpressionRef


X_WhenCondition ::= X_WhenConditionExpr
   | X_WhenConditionElse


X_WhenConditionExpr ::= X_ExpressionRef (',' X_ExpressionRef)*


X_WhenConditionElse ::= 'else'


X_tkSEMI ::= ';'


X_BinaryExprOperand ::= X_BinaryOperator X_UnaryExpr


X_BinaryOperator ::= '=='
   | '!='
   | '<='
   | '>='
   | '<'
   | '>'
   | '==='
   | '!=='
   | '+'
   | '-'
   | '*'
   | '/'
   | '%'
   | 'and'
   | 'or'
   | 'in'
   | 'not' X_tkIN
   | '?:'


X_tkIN ::= 'in'


X_RelKeyIndexClause ::= X_KeyIndexKind X_BaseAttributeDefinition (',' X_BaseAttributeDefinition)* ';'


X_KeyIndexKind ::= 'key'
   | 'index'


X_EntityBodyShort ::= ';'


X_ObjectDef ::= X_tkOBJECT X_Name '{' (X_AttributeDefinition)* '}'


X_tkOBJECT ::= 'object'


X_StructDef ::= X_StructKeyword X_Name '{' (X_AttributeDefinition)* '}'


X_StructKeyword ::= 'struct'
   | 'record'


X_EnumDef ::= X_tkENUM X_Name '{' (X_Name (',' X_Name)*)? (X_tkCOMMA)? '}'


X_tkENUM ::= 'enum'


X_tkCOMMA ::= ','


X_FunctionDef ::= X_tkFUNCTION (X_QualifiedName)? '(' (X_FormalParameter (',' X_FormalParameter)*)? ')' (':' X_Type)? X_FunctionBody


X_tkFUNCTION ::= 'function'


X_FormalParameter ::= X_AttrHeader ('=' X_Expression)?


X_FunctionBody ::= X_FunctionBodyShort
   | X_FunctionBodyFull
   | X_FunctionBodyNone


X_FunctionBodyShort ::= '=' X_Expression ';'


X_FunctionBodyFull ::= X_BlockStmt


X_BlockStmt ::= X_tkLCURL (X_StatementRef)* '}'


X_tkLCURL ::= '{'


X_StatementRef ::= X_Statement


X_Statement ::= X_EmptyStmt
   | X_VarStmt
   | X_AssignStmt
   | X_ReturnStmt
   | X_BlockStmt
   | X_IfStmt
   | X_WhenStmt
   | X_WhileStmt
   | X_ForStmt
   | X_BreakStmt
   | X_ContinueStmt
   | X_UpdateStmt
   | X_DeleteStmt
   | X_IncrementStmt
   | X_CallStmt
   | X_CreateStmt
   | X_GuardStmt


X_EmptyStmt ::= ';'


X_VarStmt ::= X_VarVal X_VarDeclarator ('=' X_Expression)? ';'


X_VarVal ::= 'val'
   | 'var'


X_VarDeclarator ::= X_SimpleVarDeclarator
   | X_TupleVarDeclarator


X_SimpleVarDeclarator ::= X_AttrHeader


X_TupleVarDeclarator ::= X_tkLPAR X_VarDeclarator (',' X_VarDeclarator)* ')'


X_AssignStmt ::= X_BaseExpr X_AssignOp X_Expression ';'


X_AssignOp ::= '='
   | '+='
   | '-='
   | '*='
   | '/='
   | '%='


X_ReturnStmt ::= X_tkRETURN (X_Expression)? ';'


X_tkRETURN ::= 'return'


X_IfStmt ::= X_tkIF '(' X_Expression ')' X_StatementRef (X_tkElse X_StatementRef)?


X_WhenStmt ::= X_tkWHEN ('(' X_ExpressionRef ')')? '{' (X_WhenStmtCase)* '}'


X_WhenStmtCase ::= X_WhenCondition '->' X_StatementRef (X_tkSEMI)*


X_WhileStmt ::= X_tkWHILE '(' X_Expression ')' X_StatementRef


X_tkWHILE ::= 'while'


X_ForStmt ::= X_tkFOR '(' X_VarDeclarator 'in' X_Expression ')' X_StatementRef


X_tkFOR ::= 'for'


X_BreakStmt ::= X_tkBREAK ';'


X_tkBREAK ::= 'break'


X_ContinueStmt ::= X_tkCONTINUE ';'


X_tkCONTINUE ::= 'continue'


X_UpdateStmt ::= X_tkUPDATE X_UpdateTarget '(' (X_UpdateWhatExpr (',' X_UpdateWhatExpr)*)? ')' ';'


X_tkUPDATE ::= 'update'


X_UpdateTarget ::= X_UpdateTargetAt
   | X_UpdateTargetExpr


X_UpdateTargetAt ::= X_AtExprFrom X_AtExprAt X_AtExprWhere


X_AtExprFrom ::= X_AtExprFromSingle
   | X_AtExprFromMulti


X_AtExprFromSingle ::= X_QualifiedName


X_AtExprFromMulti ::= X_tkLPAR X_AtExprFromItem (',' X_AtExprFromItem)* ')'


X_AtExprFromItem ::= (X_Name ':')? X_QualifiedName


X_UpdateTargetExpr ::= X_BaseExprNoCallNoAt


X_BaseExprNoCallNoAt ::= X_BaseExprHead (X_BaseExprTailNoCallNoAt)*


X_BaseExprTailNoCallNoAt ::= X_BaseExprTailMember
   | X_BaseExprTailSubscript
   | X_BaseExprTailNotNull
   | X_BaseExprTailSafeMember
   | X_BaseExprTailUnaryPostfixOp


X_UpdateWhatExpr ::= (X_UpdateWhatNameOp)? X_Expression


X_UpdateWhatNameOp ::= ('.')? X_Name X_AssignOp


X_DeleteStmt ::= X_tkDELETE X_UpdateTarget ';'


X_tkDELETE ::= 'delete'


X_IncrementStmt ::= X_IncrementOperator X_BaseExpr ';'


X_CallStmt ::= X_BaseExpr ';'


X_CreateStmt ::= X_CreateExpr ';'


X_GuardStmt ::= X_tkGUARD X_BlockStmt


X_tkGUARD ::= 'guard'


X_FunctionBodyNone ::= ';'


X_NamespaceDef ::= X_tkNAMESPACE (X_QualifiedName)? '{' (X_AnnotatedDef)* '}'


X_tkNAMESPACE ::= 'namespace'


X_ImportDef ::= X_tkIMPORT (X_Name ':')? X_ImportModule (X_ImportTarget)? ';'


X_tkIMPORT ::= 'import'


X_ImportModule ::= X_AbsoluteImportModule
   | X_RelativeImportModule
   | X_UpImportModule


X_AbsoluteImportModule ::= X_QualifiedName


X_RelativeImportModule ::= X_tkDOT (X_QualifiedName)?


X_UpImportModule ::= (X_tkCARET)+ ('.' X_QualifiedName)?


X_tkCARET ::= '^'


X_ImportTarget ::= '.' (X_ImportTargetExact | X_ImportTargetWildcard)


X_ImportTargetExact ::= '{' (X_ImportTargetExactItem (',' X_ImportTargetExactItem)*)? '}'


X_ImportTargetExactItem ::= (X_Name ':')? X_QualifiedName ('.' X_tkMUL)?


X_ImportTargetWildcard ::= '*'


X_OpDef ::= X_tkOPERATION X_Name '(' (X_FormalParameter (',' X_FormalParameter)*)? ')' X_BlockStmt


X_tkOPERATION ::= 'operation'


X_QueryDef ::= X_tkQUERY X_Name '(' (X_FormalParameter (',' X_FormalParameter)*)? ')' (':' X_Type)? X_QueryBody


X_tkQUERY ::= 'query'


X_QueryBody ::= X_FunctionBodyShort
   | X_FunctionBodyFull


X_IncludeDef ::= X_tkINCLUDE X_tkSTRING ';'


X_tkINCLUDE ::= 'include'


X_tkSTRING ::= STRING


X_ConstantDef ::= X_tkVAL X_Name (':' X_TypeRef)? '=' X_ExpressionRef ';'


X_tkVAL ::= 'val'


COMMON_INT ::= DECNUM | '0' 'x' HEXDIG+;
BIG_INTEGER ::= COMMON_INT 'L';
NUMBER ::= COMMON_INT;

STRCHAR ::= '\t' | '\\' ('b'|'t'|'n'|'f'|'r'|'"'|"'"|'\\' | 'u' HEXDIG HEXDIG HEXDIG HEXDIG)

X_tkElse ::= 'else'
X_tkLimit ::= 'limit'
X_tkOffset ::= 'offset'
X_tkArrow ::= '->'
X_tkRPAR ::= ')'
X_tkRCURL ::= '}'
X_tkRBRACK ::= ']'
