// Rell version: 0.12.0
// Timestamp: 1678830850212 (2023-03-14 21:54:10+0000)
grammar net.postchain.rellide.xtext.Rell hidden(WS, ML_COMMENT, SL_COMMENT)

import 'http://www.eclipse.org/emf/2002/Ecore' as ecore

generate rell 'http://www.postchain.net/Rell'

X_RootParser
   : {X_RootParser} (a=X_ModuleHeader)? (b+=X_AnnotatedDef)*
   ;

X_ModuleHeader
   : {X_ModuleHeader} (a+=X_Modifier)* b=X_tkMODULE ';'
   ;

X_Modifier
   : {X_Modifier_0} 'abstract'
   | {X_Modifier_1} 'override'
   | X_Annotation
   ;

X_Annotation
   : {X_Annotation} '@' a=X_Name (b=X_AnnotationArgs)?
   ;

X_Name
   : {X_Name} ID
   ;

X_AnnotationArgs
   : {X_AnnotationArgs} '(' (a+=X_AnnotationArg (',' a+=X_AnnotationArg)*)? ')'
   ;

X_AnnotationArg
   : X_AnnotationArgValue
   | X_AnnotationArgName
   ;

X_AnnotationArgValue
   : {X_AnnotationArgValue} a=X_LiteralExpr
   ;

X_LiteralExpr
   : X_IntExpr
   | X_BigIntExpr
   | X_DecimalExpr
   | X_StringExpr
   | X_BytesExpr
   | {X_LiteralExpr_5} 'false'
   | {X_LiteralExpr_6} 'true'
   | X_NullLiteralExpr
   ;

X_IntExpr
   : {X_IntExpr} NUMBER
   ;

X_BigIntExpr
   : {X_BigIntExpr} BIG_INTEGER
   ;

X_DecimalExpr
   : {X_DecimalExpr} DECIMAL
   ;

X_StringExpr
   : {X_StringExpr} STRING
   ;

X_BytesExpr
   : {X_BytesExpr} BYTES
   ;

X_NullLiteralExpr
   : {X_NullLiteralExpr} 'null'
   ;

X_AnnotationArgName
   : {X_AnnotationArgName} a=X_QualifiedName
   ;

X_QualifiedName
   : {X_QualifiedName} a+=X_Name ('.' a+=X_Name)*
   ;

X_tkMODULE
   : {X_Token} 'module'
   ;

X_AnnotatedDef
   : {X_AnnotatedDef} (a+=X_Modifier)* b=X_AnyDef
   ;

X_AnyDef
   : X_EntityDef
   | X_ObjectDef
   | X_StructDef
   | X_EnumDef
   | X_FunctionDef
   | X_NamespaceDef
   | X_ImportDef
   | X_OpDef
   | X_QueryDef
   | X_IncludeDef
   | X_ConstantDef
   ;

X_EntityDef
   : {X_EntityDef} a=X_EntityKeyword b=X_Name (c=X_EntityAnnotations)? (d=X_EntityBody)?
   ;

X_EntityKeyword
   : {X_EntityKeyword_0} 'entity'
   | {X_EntityKeyword_1} 'class'
   ;

X_EntityAnnotations
   : {X_EntityAnnotations} '(' a+=X_Name (',' a+=X_Name)* ')'
   ;

X_EntityBody
   : X_EntityBodyFull
   | X_EntityBodyShort
   ;

X_EntityBodyFull
   : {X_EntityBodyFull} '{' (a+=X_RelAnyClause)* '}'
   ;

X_RelAnyClause
   : X_RelAttributeClause
   | X_RelKeyIndexClause
   ;

X_RelAttributeClause
   : {X_RelAttributeClause} a=X_AttributeDefinition
   ;

X_AttributeDefinition
   : {X_AttributeDefinition} a=X_BaseAttributeDefinition ';'
   ;

X_BaseAttributeDefinition
   : {X_BaseAttributeDefinition} (a=X_tkMUTABLE)? b=X_AttrHeader ('=' c=X_ExpressionRef)?
   ;

X_tkMUTABLE
   : {X_Token} 'mutable'
   ;

X_AttrHeader
   : X_NameTypeAttrHeader
   | X_AnonAttrHeader
   ;

X_NameTypeAttrHeader
   : {X_NameTypeAttrHeader} a=X_Name ':' b=X_Type
   ;

X_Type
   : X_ComplexNullableType
   | X_FunctionType
   | X_BasicType
   ;

X_ComplexNullableType
   : {X_ComplexNullableType} a=X_tkLPAR b=X_TypeRef ')' '?'
   ;

X_tkLPAR
   : {X_Token} '('
   ;

X_TypeRef
   : X_Type
   ;

X_FunctionType
   : {X_FunctionType} a=X_tkLPAR (b+=X_TypeRef (',' b+=X_TypeRef)*)? ')' '->' c=X_TypeRef
   ;

X_BasicType
   : {X_BasicType} a=X_PrimaryType (b+=X_tkQUESTION)*
   ;

X_PrimaryType
   : X_GenericType
   | X_NameType
   | X_TupleType
   | X_VirtualType
   | X_MirrorStructType
   ;

X_GenericType
   : {X_GenericType} a=X_QualifiedName '<' b+=X_TypeRef (',' b+=X_TypeRef)* '>'
   ;

X_NameType
   : {X_NameType} a=X_QualifiedName
   ;

X_TupleType
   : {X_TupleType} a=X_tkLPAR b=X_TupleTypeField (c=X_TupleTypeTail)? ')'
   ;

X_TupleTypeField
   : {X_TupleTypeField} (a=X_Name ':')? b=X_TypeRef
   ;

X_TupleTypeTail
   : {X_TupleTypeTail} ',' (a+=X_TupleTypeField (',' a+=X_TupleTypeField)*)?
   ;

X_VirtualType
   : {X_VirtualType} a=X_tkVIRTUAL '<' b=X_TypeRef '>'
   ;

X_tkVIRTUAL
   : {X_Token} 'virtual'
   ;

X_MirrorStructType
   : {X_MirrorStructType} a=X_MirrorStructType0
   ;

X_MirrorStructType0
   : {X_MirrorStructType0} a=X_tkSTRUCT '<' (b=X_tkMUTABLE)? c=X_TypeRef '>'
   ;

X_tkSTRUCT
   : {X_Token} 'struct'
   ;

X_tkQUESTION
   : {X_Token} '?'
   ;

X_AnonAttrHeader
   : {X_AnonAttrHeader} a=X_QualifiedName (b=X_tkQUESTION)?
   ;

X_ExpressionRef
   : X_Expression
   ;

X_Expression
   : {X_Expression} a=X_UnaryExpr (b+=X_BinaryExprOperand)*
   ;

X_UnaryExpr
   : {X_UnaryExpr} (a+=X_UnaryPrefixOperator)* b=X_OperandExpr
   ;

X_UnaryPrefixOperator
   : {X_UnaryPrefixOperator_0} '+'
   | {X_UnaryPrefixOperator_1} '-'
   | {X_UnaryPrefixOperator_2} 'not'
   | {X_UnaryPrefixOperator_3} a=X_IncrementOperator
   ;

X_IncrementOperator
   : {X_IncrementOperator_0} '++'
   | {X_IncrementOperator_1} '--'
   ;

X_OperandExpr
   : X_BaseExpr
   | X_IfExpr
   | X_WhenExpr
   ;

X_BaseExpr
   : {X_BaseExpr} a=X_BaseExprHead (b+=X_BaseExprTail)*
   ;

X_BaseExprHead
   : X_GenericTypeExpr
   | X_NameExpr
   | X_DollarExpr
   | X_AttrExpr
   | X_IntExpr
   | X_BigIntExpr
   | X_DecimalExpr
   | X_StringExpr
   | X_BytesExpr
   | {X_BaseExprHead_9} 'false'
   | {X_BaseExprHead_10} 'true'
   | X_NullLiteralExpr
   | X_ParenthesesExpr
   | X_CreateExpr
   | X_ListLiteralExpr
   | X_EmptyMapLiteralExpr
   | X_NonEmptyMapLiteralExpr
   | X_MirrorStructExpr
   | X_VirtualTypeExpr
   ;

X_GenericTypeExpr
   : {X_GenericTypeExpr} a=X_GenericType (b=X_BaseExprTailMember | b=X_BaseExprTailCall)
   ;

X_BaseExprTailMember
   : {X_BaseExprTailMember} '.' a=X_Name
   ;

X_BaseExprTailCall
   : {X_BaseExprTailCall} a=X_CallArgs
   ;

X_CallArgs
   : {X_CallArgs} '(' (a+=X_CallArg (',' a+=X_CallArg)*)? ')'
   ;

X_CallArg
   : {X_CallArg} (a=X_Name '=')? b=X_CallArgValue
   ;

X_CallArgValue
   : {X_CallArgValue_0} '*'
   | {X_CallArgValue_1} a=X_ExpressionRef
   ;

X_NameExpr
   : {X_NameExpr} a=X_Name
   ;

X_DollarExpr
   : {X_DollarExpr} '$'
   ;

X_AttrExpr
   : {X_AttrExpr} a=X_tkDOT b=X_Name
   ;

X_tkDOT
   : {X_Token} '.'
   ;

X_ParenthesesExpr
   : {X_ParenthesesExpr} a=X_tkLPAR b=X_TupleExprField (c=X_TupleExprTail)? ')'
   ;

X_TupleExprField
   : X_TupleExprFieldNameEqExpr
   | X_TupleExprFieldNameColonExpr
   | X_TupleExprFieldExpr
   ;

X_TupleExprFieldNameEqExpr
   : {X_TupleExprFieldNameEqExpr} a=X_Name b=X_tkASSIGN c=X_ExpressionRef
   ;

X_tkASSIGN
   : {X_Token} '='
   ;

X_TupleExprFieldNameColonExpr
   : {X_TupleExprFieldNameColonExpr} a=X_Name b=X_tkCOLON c=X_ExpressionRef
   ;

X_tkCOLON
   : {X_Token} ':'
   ;

X_TupleExprFieldExpr
   : {X_TupleExprFieldExpr} a=X_ExpressionRef
   ;

X_TupleExprTail
   : {X_TupleExprTail} ',' (a+=X_TupleExprField (',' a+=X_TupleExprField)*)?
   ;

X_CreateExpr
   : {X_CreateExpr} a=X_tkCREATE b=X_QualifiedName '(' (c+=X_CreateExprArg (',' c+=X_CreateExprArg)*)? ')'
   ;

X_tkCREATE
   : {X_Token} 'create'
   ;

X_CreateExprArg
   : {X_CreateExprArg} (('.')? a=X_Name '=')? b=X_CallArgValue
   ;

X_ListLiteralExpr
   : {X_ListLiteralExpr} a=X_tkLBRACK (b+=X_ExpressionRef (',' b+=X_ExpressionRef)*)? ']'
   ;

X_tkLBRACK
   : {X_Token} '['
   ;

X_EmptyMapLiteralExpr
   : {X_EmptyMapLiteralExpr} a=X_tkLBRACK ':' ']'
   ;

X_NonEmptyMapLiteralExpr
   : {X_NonEmptyMapLiteralExpr} a=X_tkLBRACK b+=X_MapLiteralExprEntry (',' b+=X_MapLiteralExprEntry)* ']'
   ;

X_MapLiteralExprEntry
   : {X_MapLiteralExprEntry} a=X_ExpressionRef ':' b=X_ExpressionRef
   ;

X_MirrorStructExpr
   : {X_MirrorStructExpr} a=X_MirrorStructType0
   ;

X_VirtualTypeExpr
   : {X_VirtualTypeExpr} a=X_VirtualType
   ;

X_BaseExprTail
   : X_BaseExprTailMember
   | X_BaseExprTailSubscript
   | X_BaseExprTailNotNull
   | X_BaseExprTailSafeMember
   | X_BaseExprTailUnaryPostfixOp
   | X_BaseExprTailCall
   | X_BaseExprTailAt
   ;

X_BaseExprTailSubscript
   : {X_BaseExprTailSubscript} a=X_tkLBRACK b=X_ExpressionRef ']'
   ;

X_BaseExprTailNotNull
   : {X_BaseExprTailNotNull} '!!'
   ;

X_BaseExprTailSafeMember
   : {X_BaseExprTailSafeMember} '?.' a=X_Name
   ;

X_BaseExprTailUnaryPostfixOp
   : {X_BaseExprTailUnaryPostfixOp} a=X_UnaryPostfixOperator
   ;

X_UnaryPostfixOperator
   : {X_UnaryPostfixOperator_0} a=X_IncrementOperator
   | {X_UnaryPostfixOperator_1} '??'
   ;

X_BaseExprTailAt
   : {X_BaseExprTailAt} a=X_AtExprAt b=X_AtExprWhere (c=X_AtExprWhat)? (d=X_AtExprModifiers)?
   ;

X_AtExprAt
   : {X_AtExprAt_0} a=X_tkAT b=X_tkQUESTION
   | {X_AtExprAt_1} a=X_tkAT b=X_tkMUL
   | {X_AtExprAt_2} a=X_tkAT b=X_tkPLUS
   | {X_AtExprAt_3} '@'
   ;

X_tkAT
   : {X_Token} '@'
   ;

X_tkMUL
   : {X_Token} '*'
   ;

X_tkPLUS
   : {X_Token} '+'
   ;

X_AtExprWhere
   : {X_AtExprWhere} '{' (a+=X_ExpressionRef (',' a+=X_ExpressionRef)*)? '}'
   ;

X_AtExprWhat
   : X_AtExprWhatSimple
   | X_AtExprWhatComplex
   ;

X_AtExprWhatSimple
   : {X_AtExprWhatSimple} ('.' a+=X_Name)+
   ;

X_AtExprWhatComplex
   : {X_AtExprWhatComplex} '(' a+=X_AtExprWhatComplexItem (',' a+=X_AtExprWhatComplexItem)* ')'
   ;

X_AtExprWhatComplexItem
   : {X_AtExprWhatComplexItem} (a+=X_Annotation)* (b=X_AtExprWhatName)? c=X_ExpressionRef
   ;

X_AtExprWhatName
   : {X_AtExprWhatName} a=X_Name '='
   ;

X_AtExprModifiers
   : {X_AtExprModifiers_0} 'limit' a=X_ExpressionRef (b=X_AtExprOffset)?
   | {X_AtExprModifiers_1} 'offset' a=X_ExpressionRef (b=X_AtExprLimit)?
   ;

X_AtExprOffset
   : {X_AtExprOffset} 'offset' a=X_ExpressionRef
   ;

X_AtExprLimit
   : {X_AtExprLimit} 'limit' a=X_ExpressionRef
   ;

X_IfExpr
   : {X_IfExpr} a=X_tkIF '(' b=X_ExpressionRef ')' c=X_ExpressionRef 'else' d=X_ExpressionRef
   ;

X_tkIF
   : {X_Token} 'if'
   ;

X_WhenExpr
   : {X_WhenExpr} a=X_tkWHEN ('(' b=X_ExpressionRef ')')? '{' c=X_WhenExprCases '}'
   ;

X_tkWHEN
   : {X_Token} 'when'
   ;

X_WhenExprCases
   : {X_WhenExprCases} a+=X_WhenExprCase ((';')+ a+=X_WhenExprCase)* (b+=X_tkSEMI)*
   ;

X_WhenExprCase
   : {X_WhenExprCase} a=X_WhenCondition '->' b=X_ExpressionRef
   ;

X_WhenCondition
   : X_WhenConditionExpr
   | X_WhenConditionElse
   ;

X_WhenConditionExpr
   : {X_WhenConditionExpr} a+=X_ExpressionRef (',' a+=X_ExpressionRef)*
   ;

X_WhenConditionElse
   : {X_WhenConditionElse} 'else'
   ;

X_tkSEMI
   : {X_Token} ';'
   ;

X_BinaryExprOperand
   : {X_BinaryExprOperand} a=X_BinaryOperator b=X_UnaryExpr
   ;

X_BinaryOperator
   : {X_BinaryOperator_0} '=='
   | {X_BinaryOperator_1} '!='
   | {X_BinaryOperator_2} '<='
   | {X_BinaryOperator_3} '>='
   | {X_BinaryOperator_4} '<'
   | {X_BinaryOperator_5} '>'
   | {X_BinaryOperator_6} '==='
   | {X_BinaryOperator_7} '!=='
   | {X_BinaryOperator_8} '+'
   | {X_BinaryOperator_9} '-'
   | {X_BinaryOperator_10} '*'
   | {X_BinaryOperator_11} '/'
   | {X_BinaryOperator_12} '%'
   | {X_BinaryOperator_13} 'and'
   | {X_BinaryOperator_14} 'or'
   | {X_BinaryOperator_15} 'in'
   | {X_BinaryOperator_16} 'not' a=X_tkIN
   | {X_BinaryOperator_17} '?:'
   ;

X_tkIN
   : {X_Token} 'in'
   ;

X_RelKeyIndexClause
   : {X_RelKeyIndexClause} a=X_KeyIndexKind b+=X_BaseAttributeDefinition (',' b+=X_BaseAttributeDefinition)* ';'
   ;

X_KeyIndexKind
   : {X_KeyIndexKind_0} 'key'
   | {X_KeyIndexKind_1} 'index'
   ;

X_EntityBodyShort
   : {X_EntityBodyShort} ';'
   ;

X_ObjectDef
   : {X_ObjectDef} a=X_tkOBJECT b=X_Name '{' (c+=X_AttributeDefinition)* '}'
   ;

X_tkOBJECT
   : {X_Token} 'object'
   ;

X_StructDef
   : {X_StructDef} a=X_StructKeyword b=X_Name '{' (c+=X_AttributeDefinition)* '}'
   ;

X_StructKeyword
   : {X_StructKeyword_0} 'struct'
   | {X_StructKeyword_1} 'record'
   ;

X_EnumDef
   : {X_EnumDef} a=X_tkENUM b=X_Name '{' (c+=X_Name (',' c+=X_Name)*)? (d=X_tkCOMMA)? '}'
   ;

X_tkENUM
   : {X_Token} 'enum'
   ;

X_tkCOMMA
   : {X_Token} ','
   ;

X_FunctionDef
   : {X_FunctionDef} a=X_tkFUNCTION (b=X_QualifiedName)? '(' (c+=X_FormalParameter (',' c+=X_FormalParameter)*)? ')' (':' d=X_Type)? e=X_FunctionBody
   ;

X_tkFUNCTION
   : {X_Token} 'function'
   ;

X_FormalParameter
   : {X_FormalParameter} a=X_AttrHeader ('=' b=X_Expression)?
   ;

X_FunctionBody
   : X_FunctionBodyShort
   | X_FunctionBodyFull
   | X_FunctionBodyNone
   ;

X_FunctionBodyShort
   : {X_FunctionBodyShort} '=' a=X_Expression ';'
   ;

X_FunctionBodyFull
   : {X_FunctionBodyFull} a=X_BlockStmt
   ;

X_BlockStmt
   : {X_BlockStmt} a=X_tkLCURL (b+=X_StatementRef)* '}'
   ;

X_tkLCURL
   : {X_Token} '{'
   ;

X_StatementRef
   : X_Statement
   ;

X_Statement
   : X_EmptyStmt
   | X_VarStmt
   | X_AssignStmt
   | X_ReturnStmt
   | X_BlockStmt
   | X_IfStmt
   | X_WhenStmt
   | X_WhileStmt
   | X_ForStmt
   | X_BreakStmt
   | X_ContinueStmt
   | X_UpdateStmt
   | X_DeleteStmt
   | X_IncrementStmt
   | X_CallStmt
   | X_CreateStmt
   | X_GuardStmt
   ;

X_EmptyStmt
   : {X_EmptyStmt} ';'
   ;

X_VarStmt
   : {X_VarStmt} a=X_VarVal b=X_VarDeclarator ('=' c=X_Expression)? ';'
   ;

X_VarVal
   : {X_VarVal_0} 'val'
   | {X_VarVal_1} 'var'
   ;

X_VarDeclarator
   : X_SimpleVarDeclarator
   | X_TupleVarDeclarator
   ;

X_SimpleVarDeclarator
   : {X_SimpleVarDeclarator} a=X_AttrHeader
   ;

X_TupleVarDeclarator
   : {X_TupleVarDeclarator} a=X_tkLPAR b+=X_VarDeclarator (',' b+=X_VarDeclarator)* ')'
   ;

X_AssignStmt
   : {X_AssignStmt} a=X_BaseExpr b=X_AssignOp c=X_Expression ';'
   ;

X_AssignOp
   : {X_AssignOp_0} '='
   | {X_AssignOp_1} '+='
   | {X_AssignOp_2} '-='
   | {X_AssignOp_3} '*='
   | {X_AssignOp_4} '/='
   | {X_AssignOp_5} '%='
   ;

X_ReturnStmt
   : {X_ReturnStmt} a=X_tkRETURN (b=X_Expression)? ';'
   ;

X_tkRETURN
   : {X_Token} 'return'
   ;

X_IfStmt
   : {X_IfStmt} a=X_tkIF '(' b=X_Expression ')' c=X_StatementRef ('else' d=X_StatementRef)?
   ;

X_WhenStmt
   : {X_WhenStmt} a=X_tkWHEN ('(' b=X_ExpressionRef ')')? '{' (c+=X_WhenStmtCase)* '}'
   ;

X_WhenStmtCase
   : {X_WhenStmtCase} a=X_WhenCondition '->' b=X_StatementRef (c+=X_tkSEMI)*
   ;

X_WhileStmt
   : {X_WhileStmt} a=X_tkWHILE '(' b=X_Expression ')' c=X_StatementRef
   ;

X_tkWHILE
   : {X_Token} 'while'
   ;

X_ForStmt
   : {X_ForStmt} a=X_tkFOR '(' b=X_VarDeclarator 'in' c=X_Expression ')' d=X_StatementRef
   ;

X_tkFOR
   : {X_Token} 'for'
   ;

X_BreakStmt
   : {X_BreakStmt} a=X_tkBREAK ';'
   ;

X_tkBREAK
   : {X_Token} 'break'
   ;

X_ContinueStmt
   : {X_ContinueStmt} a=X_tkCONTINUE ';'
   ;

X_tkCONTINUE
   : {X_Token} 'continue'
   ;

X_UpdateStmt
   : {X_UpdateStmt} a=X_tkUPDATE b=X_UpdateTarget '(' (c+=X_UpdateWhatExpr (',' c+=X_UpdateWhatExpr)*)? ')' ';'
   ;

X_tkUPDATE
   : {X_Token} 'update'
   ;

X_UpdateTarget
   : X_UpdateTargetAt
   | X_UpdateTargetExpr
   ;

X_UpdateTargetAt
   : {X_UpdateTargetAt} a=X_AtExprFrom b=X_AtExprAt c=X_AtExprWhere
   ;

X_AtExprFrom
   : X_AtExprFromSingle
   | X_AtExprFromMulti
   ;

X_AtExprFromSingle
   : {X_AtExprFromSingle} a=X_QualifiedName
   ;

X_AtExprFromMulti
   : {X_AtExprFromMulti} a=X_tkLPAR b+=X_AtExprFromItem (',' b+=X_AtExprFromItem)* ')'
   ;

X_AtExprFromItem
   : {X_AtExprFromItem} (a=X_Name ':')? b=X_QualifiedName
   ;

X_UpdateTargetExpr
   : {X_UpdateTargetExpr} a=X_BaseExprNoCallNoAt
   ;

X_BaseExprNoCallNoAt
   : {X_BaseExprNoCallNoAt} a=X_BaseExprHead (b+=X_BaseExprTailNoCallNoAt)*
   ;

X_BaseExprTailNoCallNoAt
   : X_BaseExprTailMember
   | X_BaseExprTailSubscript
   | X_BaseExprTailNotNull
   | X_BaseExprTailSafeMember
   | X_BaseExprTailUnaryPostfixOp
   ;

X_UpdateWhatExpr
   : {X_UpdateWhatExpr} (a=X_UpdateWhatNameOp)? b=X_Expression
   ;

X_UpdateWhatNameOp
   : {X_UpdateWhatNameOp} ('.')? a=X_Name b=X_AssignOp
   ;

X_DeleteStmt
   : {X_DeleteStmt} a=X_tkDELETE b=X_UpdateTarget ';'
   ;

X_tkDELETE
   : {X_Token} 'delete'
   ;

X_IncrementStmt
   : {X_IncrementStmt} a=X_IncrementOperator b=X_BaseExpr ';'
   ;

X_CallStmt
   : {X_CallStmt} a=X_BaseExpr ';'
   ;

X_CreateStmt
   : {X_CreateStmt} a=X_CreateExpr ';'
   ;

X_GuardStmt
   : {X_GuardStmt} a=X_tkGUARD b=X_BlockStmt
   ;

X_tkGUARD
   : {X_Token} 'guard'
   ;

X_FunctionBodyNone
   : {X_FunctionBodyNone} ';'
   ;

X_NamespaceDef
   : {X_NamespaceDef} a=X_tkNAMESPACE (b=X_QualifiedName)? '{' (c+=X_AnnotatedDef)* '}'
   ;

X_tkNAMESPACE
   : {X_Token} 'namespace'
   ;

X_ImportDef
   : {X_ImportDef} a=X_tkIMPORT (b=X_Name ':')? c=X_ImportModule (d=X_ImportTarget)? ';'
   ;

X_tkIMPORT
   : {X_Token} 'import'
   ;

X_ImportModule
   : X_AbsoluteImportModule
   | X_RelativeImportModule
   | X_UpImportModule
   ;

X_AbsoluteImportModule
   : {X_AbsoluteImportModule} a=X_QualifiedName
   ;

X_RelativeImportModule
   : {X_RelativeImportModule} a=X_tkDOT (b=X_QualifiedName)?
   ;

X_UpImportModule
   : {X_UpImportModule} (a+=X_tkCARET)+ ('.' b=X_QualifiedName)?
   ;

X_tkCARET
   : {X_Token} '^'
   ;

X_ImportTarget
   : {X_ImportTarget} '.' (a=X_ImportTargetExact | a=X_ImportTargetWildcard)
   ;

X_ImportTargetExact
   : {X_ImportTargetExact} '{' (a+=X_ImportTargetExactItem (',' a+=X_ImportTargetExactItem)*)? '}'
   ;

X_ImportTargetExactItem
   : {X_ImportTargetExactItem} (a=X_Name ':')? b=X_QualifiedName ('.' c=X_tkMUL)?
   ;

X_ImportTargetWildcard
   : {X_ImportTargetWildcard} '*'
   ;

X_OpDef
   : {X_OpDef} a=X_tkOPERATION b=X_Name '(' (c+=X_FormalParameter (',' c+=X_FormalParameter)*)? ')' d=X_BlockStmt
   ;

X_tkOPERATION
   : {X_Token} 'operation'
   ;

X_QueryDef
   : {X_QueryDef} a=X_tkQUERY b=X_Name '(' (c+=X_FormalParameter (',' c+=X_FormalParameter)*)? ')' (':' d=X_Type)? e=X_QueryBody
   ;

X_tkQUERY
   : {X_Token} 'query'
   ;

X_QueryBody
   : X_FunctionBodyShort
   | X_FunctionBodyFull
   ;

X_IncludeDef
   : {X_IncludeDef} a=X_tkINCLUDE b=X_tkSTRING ';'
   ;

X_tkINCLUDE
   : {X_Token} 'include'
   ;

X_tkSTRING
   : {X_TokenString} STRING
   ;

X_ConstantDef
   : {X_ConstantDef} a=X_tkVAL b=X_Name (':' c=X_TypeRef)? '=' d=X_ExpressionRef ';'
   ;

X_tkVAL
   : {X_Token} 'val'
   ;

terminal ML_COMMENT: '/*' -> '*/';
terminal SL_COMMENT: '//' !('\n'|'\r')* ('\r'? '\n')?;
terminal WS: (' '|'\t'|'\r'|'\n')+;

terminal ID: ('A'..'Z'|'a'..'z'|'_') ('A'..'Z'|'a'..'z'|'_'|'0'..'9')*;

terminal DECNUM: ('0'..'9')+;
terminal EXPONENT: ('E'|'e') ('+'|'-')? DECNUM ;
terminal DECIMAL: DECNUM? '.' DECNUM EXPONENT? | DECNUM EXPONENT ;

terminal HEXDIG: '0'..'9'|'A'..'F'|'a'..'f';
terminal COMMON_INT: DECNUM | '0' 'x' HEXDIG+;
terminal BIG_INTEGER: COMMON_INT 'L';
terminal NUMBER: COMMON_INT;

terminal BYTES: 'x' (('\'' (HEXDIG HEXDIG)* '\'') | ('"' (HEXDIG HEXDIG)* '"'));

terminal STRCHAR: '\t' | '\\' ('b'|'t'|'n'|'f'|'r'|'"'|"'"|'\\' | 'u' HEXDIG HEXDIG HEXDIG HEXDIG);
terminal STRBAD: '\\' | '\u0000' .. '\u001F';
terminal STRING: '"' ( STRCHAR | !('"'|STRBAD) )*  '"' | "'" ( STRCHAR | !("'"|STRBAD) )* "'";
