{
  parserClass="net.postchain.rellide.jetbrains.language.parser.RellParser"
  parserUtilClass="net.postchain.rellide.jetbrains.language.parser.RellParserUtil"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Rell"
  psiImplClassSuffix="Impl"
  psiPackage="net.postchain.rellide.jetbrains.language.psi"
  psiImplPackage="net.postchain.rellide.jetbrains.language.psi.impl"

  elementTypeHolderClass="net.postchain.rellide.jetbrains.language.psi.RellTypes"
  elementTypeClass="net.postchain.rellide.jetbrains.language.psi.RellElementType"
  tokenTypeClass="net.postchain.rellide.jetbrains.language.psi.RellTokenType"

  psiImplUtilClass="net.postchain.rellide.jetbrains.language.psi.impl.RellPsiImplUtil"

  tokens=[
    space='regexp:\s+'
    booleanLiteral='regexp:true|false'

    SL_COMMENT="regexp://.*"
    ML_COMMENT="regexp:/\*([^*]|[\r\n]|(\*+([^*/]|[\r\n])))*\*+/"

    WS="regexp:[ \t\r\n]+"
    ID='regexp:[a-zA-Z_][a-zA-Z_0-9]*'
    DECNUM="regexp:[0-9]+"
    HEXDIGNUM="regexp:0\s*x\s*[0-9A-Fa-f]+"
    DECIMAL="regexp:[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?"
    HEXDIG="regexp:[0-9A-Fa-f]"
    BYTES="regexp:x(('([_0-9a-fA-F][_0-9a-fA-F])*')|(\"([_0-9a-fA-F][_0-9a-fA-F])*\"))"
    STRBAD="regexp:\\|'\u0000' .. '\u001F'"
    STRING_NOT_CLOSED="regexp:(\"(\t|\\[btnfr\"\'\\]|\\u[0-9A-Fa-f]{4}|[^\"\\\u0000-\u001F])*)|('(\t|\\[btnfr\"\'\\]|\\u[0-9A-Fa-f]{4}|[^\'\\\u0000-\u001F])*)"
    STRING="regexp:(\"(\t|\\[btnfr\"\'\\]|\\u[0-9A-Fa-f]{4}|[^\"\\\u0000-\u001F])*\")|('(\t|\\[btnfr\"\'\\]|\\u[0-9A-Fa-f]{4}|[^\'\\\u0000-\u001F])*\')"

    X_tkCOMMA=','
    X_NullLiteralExpr='null'
    X_tkMODULE='module'
    X_tkMUTABLE='mutable'
    X_tkLPAR='('
    X_tkVIRTUAL='virtual'
    X_tkSTRUCT='struct'
    X_tkQUESTION='?'
    X_DollarExpr='$'
    X_tkDOT='.'
    X_tkASSIGN='='
    X_tkCOLON=':'
    X_tkCREATE='create'
    X_tkLBRACK='['
    X_BaseExprTailNotNull='!!'
    X_tkAT='@'
    X_tkMUL='*'
    X_tkPLUS='+'
    X_tkIF='if'
    X_tkWHEN='when'
    X_tkSEMI=';'
    X_tkIN='in'
    X_tkOBJECT='object'
    X_tkENUM='enum'
    X_tkFUNCTION='function'
    X_tkLCURL='{'
    X_tkRETURN='return'
    X_tkWHILE='while'
    X_tkFOR='for'
    X_tkBREAK='break'
    X_tkCONTINUE='continue'
    X_tkUPDATE='update'
    X_tkDELETE='delete'
    X_tkGUARD='guard'
    X_tkNAMESPACE='namespace'
    X_tkIMPORT='import'
    X_tkCARET='^'
    X_tkOPERATION='operation'
    X_tkQUERY='query'
    X_tkINCLUDE='include'
    X_tkVAL='val'
    X_tkElse='else'
    X_tkLimit='limit'
    X_tkOffset='offset'
    X_tkArrow='->'
    X_tkRPAR=')'
    X_tkRCURL='}'
    X_tkRBRACK=']'
    X_tkLT='<'
    X_tkGT='>'
  ]
}
X_RootParser ::= (X_ModuleHeader)? (X_AnnotatedDef)*


X_ModuleHeader ::= (X_Modifier)* X_tkMODULE X_tkSEMI


X_Modifier ::= 'abstract'
   | 'override'
   | X_Annotation


X_Annotation ::= X_tkAT X_Name (X_AnnotationArgs)?


X_Name ::= ID


X_AnnotationArgs ::= X_CommaSeparated_7


X_CommaSeparated_7 ::= X_tkLPAR (X_CommaSeparated_6)? X_tkRPAR


X_CommaSeparated_6 ::= X_AnnotationArg (X_tkCOMMA X_AnnotationArg)* (X_tkCOMMA)?


X_AnnotationArg ::= X_AnnotationArgValue
   | X_AnnotationArgName


X_AnnotationArgValue ::= X_LiteralExpr

X_LiteralExpr ::= X_BigIntExpr
   | X_IntExpr
   | X_DecimalExpr
   | X_StringExpr
   | X_BytesExpr
   | 'false'
   | 'true'
   | X_NullLiteralExpr


X_IntExpr ::= NUMBER


X_BigIntExpr ::= BIG_INTEGER


X_DecimalExpr ::= DECIMAL


X_StringExpr ::= STRING


X_BytesExpr ::= BYTES


X_AnnotationArgName ::= X_QualifiedName


X_QualifiedName ::= X_Name (X_tkDOT X_Name)*


X_AnnotatedDef ::= (X_Modifier)* X_AnyDef


X_AnyDef ::= X_EntityDef
   | X_ObjectDef
   | X_StructDef
   | X_EnumDef
   | X_FunctionDef
   | X_NamespaceDef
   | X_ImportDef
   | X_OpDef
   | X_QueryDef
   | X_IncludeDef
   | X_ConstantDef


X_EntityDef ::= X_EntityKeyword X_Name (X_EntityAnnotations)? (X_EntityBody)?


X_EntityKeyword ::= 'entity'
   | 'class'


X_EntityAnnotations ::= X_CommaSeparated_10


X_CommaSeparated_10 ::= X_tkLPAR X_CommaSeparated_9 X_tkRPAR


X_CommaSeparated_9 ::= X_Name (X_tkCOMMA X_Name)* (X_tkCOMMA)?


X_EntityBody ::= X_EntityBodyFull
   | X_EntityBodyShort

X_EntityBodyShort ::= X_tkSEMI

X_EntityBodyFull ::= X_tkLCURL (X_RelAnyClause)* X_tkRCURL


X_RelAnyClause ::= X_RelAttributeClause
   | X_RelKeyIndexClause


X_RelAttributeClause ::= X_AttributeDefinition


X_AttributeDefinition ::= X_BaseAttributeDefinition X_tkSEMI


X_BaseAttributeDefinition ::= (X_tkMUTABLE)? X_AttrHeader (X_tkASSIGN X_ExpressionRef)?


X_AttrHeader ::= X_NameTypeAttrHeader
   | X_AnonAttrHeader


X_NameTypeAttrHeader ::= X_Name X_tkCOLON X_Type


X_Type ::= X_ComplexNullableType
   | X_FunctionType
   | X_BasicType


X_ComplexNullableType ::= X_tkLPAR X_TypeRef X_tkRPAR X_tkQUESTION


X_TypeRef ::= X_Type


X_FunctionType ::= X_CommaSeparated_5 X_tkArrow X_TypeRef


X_CommaSeparated_5 ::= X_tkLPAR (X_CommaSeparated_4)? X_tkRPAR


X_CommaSeparated_4 ::= X_TypeRef (X_tkCOMMA X_TypeRef)* (X_tkCOMMA)?


X_BasicType ::= X_PrimaryType (X_tkQUESTION)*


X_PrimaryType ::= X_GenericType
   | X_NameType
   | X_TupleType
   | X_VirtualType
   | X_MirrorStructType


X_GenericType ::= X_QualifiedName X_CommaSeparated_3


X_CommaSeparated_3 ::= X_tkLT X_CommaSeparated_2 X_tkGT


X_CommaSeparated_2 ::= X_TypeRef (X_tkCOMMA X_TypeRef)* (X_tkCOMMA)?


X_NameType ::= X_QualifiedName


X_TupleType ::= X_CommaSeparated_1


X_CommaSeparated_1 ::= X_tkLPAR X_CommaSeparated_0 X_tkRPAR


X_CommaSeparated_0 ::= X_TupleTypeField (X_tkCOMMA X_TupleTypeField)* (X_tkCOMMA)?


X_TupleTypeField ::= (X_Name X_tkCOLON)? X_TypeRef


X_VirtualType ::= X_tkVIRTUAL X_tkLT X_TypeRef X_tkGT


X_MirrorStructType ::= X_MirrorStructType0


X_MirrorStructType0 ::= X_tkSTRUCT X_tkLT (X_tkMUTABLE)? X_TypeRef X_tkGT


X_AnonAttrHeader ::= X_QualifiedName (X_tkQUESTION)?


X_ExpressionRef ::= X_Expression


X_Expression ::= X_UnaryExpr (X_BinaryExprOperand)*


X_UnaryExpr ::= (X_UnaryPrefixOperator)* X_OperandExpr


X_UnaryPrefixOperator ::= X_tkPLUS
   | '-'
   | 'not'
   | X_IncrementOperator


X_IncrementOperator ::= '++'
   | '--'


X_OperandExpr ::= X_BaseExpr
   | X_IfExpr
   | X_WhenExpr


X_BaseExpr ::= X_BaseExprHead (X_BaseExprTail)*

X_BaseExprHead ::= X_GenericTypeExpr
   | X_AtExpr
   | X_NameExpr
   | X_DollarExpr
   | X_AttrExpr
   | X_BigIntExpr
   | X_IntExpr
   | X_DecimalExpr
   | X_StringExpr
   | X_BytesExpr
   | 'false'
   | 'true'
   | X_NullLiteralExpr
   | X_TupleExpr
   | X_CreateExpr
   | X_ListLiteralExpr
   | X_EmptyMapLiteralExpr
   | X_NonEmptyMapLiteralExpr
   | X_MirrorStructExpr
   | X_VirtualTypeExpr


X_GenericTypeExpr ::= X_GenericType (X_BaseExprTailMember | X_BaseExprTailCall)


X_BaseExprTailMember ::= X_tkDOT X_Name


X_BaseExprTailCall ::= X_CallArgs


X_CallArgs ::= X_CommaSeparated_28


X_CommaSeparated_28 ::= X_tkLPAR (X_CommaSeparated_27)? X_tkRPAR


X_CommaSeparated_27 ::= X_CallArg (X_tkCOMMA X_CallArg)* (X_tkCOMMA)?


X_CallArg ::= (X_Name X_tkASSIGN)? X_CallArgValue


X_CallArgValue ::= X_tkMUL
   | X_ExpressionRef

X_AtExpr ::= X_AtExprFrom X_BaseExprTailAt


X_AtExprFrom ::= X_CommaSeparated_16


X_CommaSeparated_16 ::= X_tkLPAR X_CommaSeparated_15 X_tkRPAR


X_CommaSeparated_15 ::= X_AtExprFromItem (X_tkCOMMA X_AtExprFromItem)* (X_tkCOMMA)?


X_AtExprFromItem ::= (X_Annotation)* (X_Name X_tkCOLON)? X_ExpressionRef


X_AtExprWhere ::= X_CommaSeparated_20


X_CommaSeparated_20 ::= X_tkLCURL (X_CommaSeparated_19)? X_tkRCURL


X_CommaSeparated_19 ::= X_ExpressionRef (X_tkCOMMA X_ExpressionRef)* (X_tkCOMMA)?

X_AtExprWhat ::= X_AtExprWhatSimple
   | X_AtExprWhatComplex

X_AtExprWhatSimple ::= X_tkDOT X_Name (X_tkDOT X_Name)*

X_AtExprWhatComplex ::= X_CommaSeparated_18


X_CommaSeparated_18 ::= X_tkLPAR X_CommaSeparated_17 X_tkRPAR


X_CommaSeparated_17 ::= X_AtExprWhatComplexItem (X_tkCOMMA X_AtExprWhatComplexItem)* (X_tkCOMMA)?


X_AtExprWhatComplexItem ::= (X_Annotation)* (X_AtExprWhatName)? X_ExpressionRef

X_NameExpr ::= X_Name


X_AttrExpr ::= X_tkDOT X_Name


X_TupleExpr ::= X_CommaSeparated_14


X_CommaSeparated_14 ::= X_tkLPAR X_CommaSeparated_13 X_tkRPAR


X_CommaSeparated_13 ::= X_TupleExprField (X_tkCOMMA X_TupleExprField)* (X_tkCOMMA)?


X_TupleExprField ::= (X_Name X_tkASSIGN)? X_ExpressionRef


X_CreateExpr ::= X_tkCREATE X_QualifiedName X_CreateExprArgs


X_CreateExprArgs ::= X_CommaSeparated_26


X_CommaSeparated_26 ::= X_tkLPAR (X_CommaSeparated_25)? X_tkRPAR


X_CommaSeparated_25 ::= X_CreateExprArg (X_tkCOMMA X_CreateExprArg)* (X_tkCOMMA)?


X_CreateExprArg ::= ((X_tkDOT)? X_Name X_tkASSIGN)? X_CallArgValue


X_ListLiteralExpr ::= X_CommaSeparated_22


X_CommaSeparated_22 ::= X_tkLBRACK (X_CommaSeparated_21)? X_tkRBRACK


X_CommaSeparated_21 ::= X_ExpressionRef (X_tkCOMMA X_ExpressionRef)* (X_tkCOMMA)?


X_EmptyMapLiteralExpr ::= X_tkLBRACK X_tkCOLON X_tkRBRACK


X_NonEmptyMapLiteralExpr ::= X_CommaSeparated_24


X_CommaSeparated_24 ::= X_tkLBRACK X_CommaSeparated_23 X_tkRBRACK


X_CommaSeparated_23 ::= X_MapLiteralExprEntry (X_tkCOMMA X_MapLiteralExprEntry)* (X_tkCOMMA)?


X_MapLiteralExprEntry ::= X_ExpressionRef X_tkCOLON X_ExpressionRef


X_MirrorStructExpr ::= X_MirrorStructType0


X_VirtualTypeExpr ::= X_VirtualType


X_BaseExprTail ::= X_BaseExprTailMember
   | X_BaseExprTailSubscript
   | X_BaseExprTailNotNull
   | X_BaseExprTailSafeMember
   | X_BaseExprTailUnaryPostfixOp
   | X_BaseExprTailCall
   | X_BaseExprTailAt


X_BaseExprTailSubscript ::= X_tkLBRACK X_ExpressionRef X_tkRBRACK


X_BaseExprTailSafeMember ::= '?.' X_Name


X_BaseExprTailUnaryPostfixOp ::= X_UnaryPostfixOperator


X_UnaryPostfixOperator ::= X_IncrementOperator
   | '??'


X_BaseExprTailAt ::= X_AtExprAt X_AtExprWhere (X_AtExprWhat)? (X_AtExprModifiers)?


X_AtExprAt ::= X_tkAT X_tkQUESTION
   | X_tkAT X_tkMUL
   | X_tkAT X_tkPLUS
   | X_tkAT


X_AtExprWhere ::= X_tkLCURL (X_ExpressionRef (X_tkCOMMA X_ExpressionRef)*)? X_tkRCURL


X_AtExprWhat ::= X_AtExprWhatSimple
   | X_AtExprWhatComplex


X_AtExprWhatComplex ::= X_tkLPAR X_AtExprWhatComplexItem (X_tkCOMMA X_AtExprWhatComplexItem)* X_tkRPAR


X_AtExprWhatComplexItem ::= (X_Annotation)* (X_AtExprWhatName)? X_ExpressionRef


X_AtExprWhatName ::= X_Name X_tkASSIGN


X_AtExprModifiers ::= X_tkLimit X_ExpressionRef (X_AtExprOffset)?
   | X_tkOffset X_ExpressionRef (X_AtExprLimit)?


X_AtExprOffset ::= X_tkOffset X_ExpressionRef


X_AtExprLimit ::= X_tkLimit X_ExpressionRef


X_IfExpr ::= X_tkIF X_tkLPAR X_ExpressionRef X_tkRPAR X_ExpressionRef X_tkElse X_ExpressionRef


X_WhenExpr ::= X_tkWHEN (X_tkLPAR X_ExpressionRef X_tkRPAR)? X_tkLCURL X_WhenExprCases X_tkRCURL


X_WhenExprCases ::= X_WhenExprCase ((X_tkSEMI)+ X_WhenExprCase)* (X_tkSEMI)*


X_WhenExprCase ::= X_WhenCondition X_tkArrow X_ExpressionRef


X_WhenCondition ::= X_WhenConditionExpr
   | X_WhenConditionElse

X_WhenConditionElse ::= X_tkElse

X_WhenConditionExpr ::= X_ExpressionRef (X_tkCOMMA X_ExpressionRef)* (X_tkCOMMA)?


X_BinaryExprOperand ::= X_BinaryOperator X_UnaryExpr


X_BinaryOperator ::= '=='
   | '!='
   | '<='
   | '>='
   | X_tkLT
   | X_tkGT
   | '==='
   | '!=='
   | X_tkPLUS
   | '-'
   | X_tkMUL
   | '/'
   | '%'
   | 'and'
   | 'or'
   | X_tkIN
   | 'not' X_tkIN
   | '?:'


X_RelKeyIndexClause ::= X_KeyIndexKind X_CommaSeparated_8 X_tkSEMI


X_CommaSeparated_8 ::= X_BaseAttributeDefinition (X_tkCOMMA X_BaseAttributeDefinition)* (X_tkCOMMA)?


X_KeyIndexKind ::= 'key'
   | 'index'



X_ObjectDef ::= X_tkOBJECT X_Name X_tkLCURL (X_AttributeDefinition)* X_tkRCURL



X_StructDef ::= X_StructKeyword X_Name X_tkLCURL (X_AttributeDefinition)* X_tkRCURL


X_StructKeyword ::= X_tkSTRUCT
   | 'record'


X_EnumDef ::= X_tkENUM X_Name X_CommaSeparated_12


X_CommaSeparated_12 ::= X_tkLCURL (X_CommaSeparated_11)? X_tkRCURL


X_CommaSeparated_11 ::= X_Name (X_tkCOMMA X_Name)* (X_tkCOMMA)?


X_FunctionDef ::= X_tkFUNCTION (X_QualifiedName)? X_FormalParameters (X_tkCOLON X_Type)? X_FunctionBody

X_FormalParameters ::= X_CommaSeparated_36

X_CommaSeparated_36 ::= X_tkLPAR (X_CommaSeparated_35)? X_tkRPAR

X_CommaSeparated_35 ::= X_FormalParameter (X_tkCOMMA X_FormalParameter)* (X_tkCOMMA)?


X_FormalParameter ::= X_AttrHeader (X_tkASSIGN X_Expression)?


X_FunctionBody ::= X_FunctionBodyShort
   | X_FunctionBodyFull
   | X_FunctionBodyNone

X_FunctionBodyNone ::= X_tkSEMI

X_FunctionBodyShort ::= X_tkASSIGN X_Expression X_tkSEMI


X_FunctionBodyFull ::= X_BlockStmt


X_BlockStmt ::= X_tkLCURL (X_StatementRef)* X_tkRCURL


X_StatementRef ::= X_Statement


X_Statement ::= X_EmptyStmt
   | X_VarStmt
   | X_AssignStmt
   | X_ReturnStmt
   | X_BlockStmt
   | X_IfStmt
   | X_WhenStmt
   | X_WhileStmt
   | X_ForStmt
   | X_BreakStmt
   | X_ContinueStmt
   | X_UpdateStmt
   | X_DeleteStmt
   | X_IncrementStmt
   | X_CallStmt
   | X_CreateStmt
   | X_GuardStmt

X_EmptyStmt ::= X_tkSEMI

X_VarStmt ::= X_VarVal X_VarDeclarator (X_tkASSIGN X_Expression)? X_tkSEMI


X_VarVal ::= X_tkVAL
   | 'var'


X_VarDeclarator ::= X_SimpleVarDeclarator
   | X_TupleVarDeclarator


X_SimpleVarDeclarator ::= X_AttrHeader


X_TupleVarDeclarator ::= X_CommaSeparated_30

X_CommaSeparated_30 ::= X_tkLPAR X_CommaSeparated_29 X_tkRPAR

X_CommaSeparated_29 ::= X_VarDeclarator (X_tkCOMMA X_VarDeclarator)* (X_tkCOMMA)?

X_AssignStmt ::= X_BaseExpr X_AssignOp X_Expression X_tkSEMI


X_AssignOp ::= X_tkASSIGN
   | '+='
   | '-='
   | '*='
   | '/='
   | '%='


X_ReturnStmt ::= X_tkRETURN (X_Expression)? X_tkSEMI


X_IfStmt ::= X_tkIF X_tkLPAR X_Expression X_tkRPAR X_StatementRef (X_tkElse X_StatementRef)?


X_WhenStmt ::= X_tkWHEN (X_tkLPAR X_ExpressionRef X_tkRPAR)? X_tkLCURL (X_WhenStmtCase)* X_tkRCURL


X_WhenStmtCase ::= X_WhenCondition X_tkArrow X_StatementRef (X_tkSEMI)*


X_WhileStmt ::= X_tkWHILE X_tkLPAR X_Expression X_tkRPAR X_StatementRef


X_ForStmt ::= X_tkFOR X_tkLPAR X_VarDeclarator X_tkIN X_Expression X_tkRPAR X_StatementRef


X_BreakStmt ::= X_tkBREAK X_tkSEMI


X_ContinueStmt ::= X_tkCONTINUE X_tkSEMI


X_UpdateStmt ::= X_tkUPDATE X_UpdateTarget X_UpdateWhat ';'



X_UpdateTarget ::= X_UpdateTargetAt
   | X_UpdateTargetExpr


X_UpdateTargetAt ::= X_UpdateFrom X_AtExprAt X_AtExprWhere


X_UpdateFrom ::= X_UpdateFromSingle
   | X_UpdateFromMulti


X_UpdateFromSingle ::= X_QualifiedName


X_UpdateFromMulti ::= X_CommaSeparated_32


X_CommaSeparated_32 ::= X_tkLPAR X_CommaSeparated_31 X_tkRPAR


X_CommaSeparated_31 ::= X_UpdateFromItem (X_tkCOMMA X_UpdateFromItem)* (X_tkCOMMA)?

X_UpdateFromItem ::= (X_Name X_tkCOLON)? X_QualifiedName

X_UpdateTargetExpr ::= X_BaseExprNoCallNoAt


X_BaseExprNoCallNoAt ::= X_BaseExprHead (X_BaseExprTailNoCallNoAt)*


X_BaseExprTailNoCallNoAt ::= X_BaseExprTailMember
   | X_BaseExprTailSubscript
   | X_BaseExprTailNotNull
   | X_BaseExprTailSafeMember
   | X_BaseExprTailUnaryPostfixOp

X_UpdateWhat ::= X_CommaSeparated_34


X_CommaSeparated_34 ::= X_tkLPAR X_CommaSeparated_33 X_tkRPAR


X_CommaSeparated_33 ::= X_UpdateWhatExpr (X_tkCOMMA X_UpdateWhatExpr)* (X_tkCOMMA)?


X_UpdateWhatExpr ::= (X_UpdateWhatNameOp)? X_Expression


X_UpdateWhatNameOp ::= (X_tkDOT)? X_Name X_AssignOp


X_DeleteStmt ::= X_tkDELETE X_UpdateTarget X_tkSEMI


X_IncrementStmt ::= X_IncrementOperator X_BaseExpr X_tkSEMI


X_CallStmt ::= X_BaseExpr X_tkSEMI


X_CreateStmt ::= X_CreateExpr X_tkSEMI


X_GuardStmt ::= X_tkGUARD X_BlockStmt


X_NamespaceDef ::= X_tkNAMESPACE (X_QualifiedName)? X_tkLCURL (X_AnnotatedDef)* X_tkRCURL


X_ImportDef ::= X_tkIMPORT (X_Name X_tkCOLON)? X_ImportModule (X_ImportTarget)? X_tkSEMI


X_ImportModule ::= X_AbsoluteImportModule
   | X_RelativeImportModule
   | X_UpImportModule


X_AbsoluteImportModule ::= X_QualifiedName


X_RelativeImportModule ::= X_tkDOT (X_QualifiedName)?


X_UpImportModule ::= (X_tkCARET)+ (X_tkDOT X_QualifiedName)?


X_ImportTarget ::= X_tkDOT (X_ImportTargetExact | X_ImportTargetWildcard)

X_ImportTargetWildcard ::= X_tkMUL

X_ImportTargetExact ::= X_CommaSeparated_38


X_CommaSeparated_38 ::= X_tkLCURL X_CommaSeparated_37 X_tkRCURL


X_CommaSeparated_37 ::= X_ImportTargetExactItem (X_tkCOMMA X_ImportTargetExactItem)* (X_tkCOMMA)?


X_ImportTargetExactItem ::= (X_Name X_tkCOLON)? X_QualifiedName (X_tkDOT X_tkMUL)?


X_OpDef ::= X_tkOPERATION X_Name X_FormalParameters X_BlockStmt


X_QueryDef ::= X_tkQUERY X_Name X_FormalParameters (X_tkCOLON X_Type)? X_QueryBody

X_QueryBody ::= X_FunctionBodyShort
   | X_FunctionBodyFull


X_IncludeDef ::= X_tkINCLUDE X_tkSTRING X_tkSEMI


X_tkSTRING ::= STRING


X_ConstantDef ::= X_tkVAL X_Name (X_tkCOLON X_TypeRef)? X_tkASSIGN X_ExpressionRef X_tkSEMI

COMMON_INT ::= HEXDIGNUM | DECNUM;
BIG_INTEGER ::= COMMON_INT 'L';
NUMBER ::= COMMON_INT;

STRCHAR ::= '\t' | '\\' ('b'|'t'|'n'|'f'|'r'|'"'|"'"|'\\' | 'u' HEXDIG HEXDIG HEXDIG HEXDIG)

