image: gradle:8.4.0-jdk17

definitions:
  steps:
    - step: &build-and-test-step
        name: Build and Test IntelliJ Plugin
        caches:
          - gradle
        script:
          - chmod +x ./gradlew
          - echo "Starting build..."
          - ./gradlew buildPlugin
          - echo "Build finished"
          - echo "Starting testing..."
          - ./gradlew test
          - echo "Tests finished"
        artifacts:
          - build/distributions/*.zip

pipelines:
  pull-requests:
    '**':
      - step: *build-and-test-step