image: adoptopenjdk/openjdk11:alpine

definitions:
  steps:
    - step: &build-and-test-step
        name: Build and Test IntelliJ Plugin
        caches:
          - gradle
        script:
          - chmod +x ./gradlew
          - echo "Starting build..."
          - ./gradlew buildPlugin
          - echo "Build finished"
          - echo "Starting testing..."
          - ./gradlew check
          - echo "Tests finished"
        artifacts:
          - build/distributions/*.zip
    - step: &publish-step
        name: Publish Plugin to Marketplace
        deployment: production
        trigger: 'manual'
        script:
          - ./gradlew publishPlugin
          - echo "Publishing finished"
        artifacts:
          - build/distributions/*.zip

pipelines:
  default:
    - step: *build-and-test-step
  branches:
    release/*:
      - step: *publish-step
  pull-requests:
    '**':
      - step: *build-and-test-step